- src/main/resources/static/elements/taskboard/aspect-item-filter.html
- src/main/resources/static/elements/taskboard/aspects-filter.html
- src/main/resources/static/elements/taskboard/board-lane.html
- src/main/resources/static/elements/taskboard/board-search.html
- src/main/resources/static/elements/taskboard/board-step.html
- src/main/resources/static/elements/taskboard/board-table.html
- src/main/resources/static/elements/taskboard/config-lane-team.html
- src/main/resources/static/elements/taskboard/config-level-item.html
- src/main/resources/static/elements/taskboard/config-level.html
- src/main/resources/static/elements/taskboard/config-table.html
- src/main/resources/static/elements/taskboard/config-visibility.html
- src/main/resources/static/elements/taskboard/issue-detail.html
- src/main/resources/static/elements/taskboard/issue-item.html
- src/main/resources/static/elements/taskboard/taskboard-home.html
- src/main/resources/static/elements/taskboard/user-account.html
- src/main/resources/static/styles/main.css
The stages colors need an update in the database:
- From '#adb5df' to '#5d70d4';
- From '#ffaaa5' to  '#a1423c';
- From '#9dd5c0' to '#68c3a1'.
> [TOOLS-27] UX tests for Taskboard

- src/main/java/objective/taskboard/issueBuffer/IssueBufferService.java
- src/main/resources/static/elements/security/log-in.html
- src/main/resources/static/elements/taskboard/board-lane.html
- src/main/resources/static/elements/taskboard/issue-detail.html
- src/main/resources/static/elements/taskboard/issue-item-synthetic.html
- src/main/resources/static/elements/taskboard/issue-item.html
- Deferred subtasks fix;
- New Synthetic View style;
- Canceled icon fix;
- Login style updated;
- Firefox: Board lane shadow fix.
> [TOOLS-52] Fix - Deferred subtasks

- pom.xml
- src/main/java/objective/taskboard/utils/XmlUtils.java
forces using apache xerces and xalan implementations
- OpenJDK8 implementation throws some exception when handling xml documents
> bugfix validate template

- src/main/java/objective/taskboard/followup/FollowUpTemplateStorage.java
- src/main/java/objective/taskboard/followup/data/Template.java
- src/main/java/objective/taskboard/followup/impl/DefaultFollowUpFacade.java
- src/main/java/objective/taskboard/followup/impl/DefaultFollowUpTemplateStorage.java
- src/main/java/objective/taskboard/followup/impl/DefaultTemplateService.java
- src/main/resources/static/elements/taskboard/followup-crud-modal.html
- src/main/resources/static/elements/taskboard/followup-dialog.html
- src/test/java/objective/taskboard/followup/FollowUpFacadeTest.java
bugfix client-side followup-dialog.html glitches
bugfix firefox-only bug when submitting form
> bugfix server-side update template without new file

- README.md
Add troubleshooting section to the README file
> Troubleshooting section

- src/main/resources/static/elements/taskboard/board-lane.html
- src/main/resources/static/elements/taskboard/board-search.html
- src/main/resources/static/elements/taskboard/board-step.html
- src/main/resources/static/elements/taskboard/issue-item.html
- src/main/resources/static/elements/taskboard/taskboard-home.html
- src/main/resources/static/scripts/searchFilter.js
- src/main/resources/static/scripts/taskboard.js
- test/board-search-test.html
- refactored hierarchical filter
- board-search is restored when removing hierarchical filter
> [TOOLS-310] issue no longer disappear on transition

- bower.json
- src/main/java/objective/taskboard/config/SecurityConfiguration.java
- src/main/java/objective/taskboard/controller/FollowUpController.java
- src/main/resources/static/elements/taskboard/followup-dialog.html
- src/main/resources/templates/index.html
- shows spinner and disables generate button until followup is generated
- same date formatting for today and selected date for followup filename
- fixed truncated followup filename when template filename has spaces
> [TOOLS-619] fix websocket gets disconnected when downloading followup

- src/main/java/objective/taskboard/controller/ResourceNotFoundException.java
- src/main/java/objective/taskboard/data/CustomField.java
- src/main/java/objective/taskboard/data/Issue.java
- src/main/java/objective/taskboard/domain/IssueStateHashCalculator.java
- src/main/resources/static/elements/taskboard/board-table.html
- src/main/resources/static/elements/taskboard/issue-detail.html
- src/main/resources/static/elements/taskboard/issue-item-synthetic.html
- src/main/resources/static/elements/taskboard/issue-item.html
- src/main/resources/static/scripts/taskboard.js
- src/main/resources/templates/index.html
- src/test/java/objective/taskboard/domain/IssueStateHashCalculatorTest.java
- src/test/resources/objective-jira-teste/search0.json
A refactoring to remove some business logic from the frontend
> [TOOLS-58] stop using "customFields" in the frontend

- src/main/resources/static/elements/taskboard/kpis/widget-cfd.html
- src/main/resources/static/elements/taskboard/kpis/widget-planned-x-ballpark.html
- src/main/resources/static/elements/taskboard/kpis/widget-progress-chart.html
- src/main/resources/static/elements/taskboard/kpis/widget-scope-by-type.html
- src/main/resources/static/elements/taskboard/kpis/widget-scope-progress.html
- src/main/resources/static/elements/taskboard/kpis/widget-wrap.html
- src/main/resources/static/scripts/dc-utils.js
- src/main/resources/static/scripts/utils.js
as agreed in this moment,
the download function is disabled for MS Edge browser and will be opened a new issue to handle this in a second moment.
> [TOOLS-596] Charts downloaded as picture- firefox/edge compatibility fix

- pom.xml
- src/main/java/objective/taskboard/Application.java
- src/main/java/objective/taskboard/CacheGenerate.java
- src/main/java/objective/taskboard/MainClassRunner.java
- src/main/java/objective/taskboard/TaskboardProperties.java
- src/main/java/objective/taskboard/config/SchedulerConfig.java
- src/main/java/objective/taskboard/followup/FollowUpHistoryKeeperInitializer.java
Was made the main class CacheGenerate to create the issue cache file and when the CacheGenerate was completed, the main classe CacheGenerate main will be terminated.
> [TOOLS-729] Was created the MainClassRunner that will execute a main rom a given argument

- src/main/java/objective/taskboard/data/Issue.java
- src/main/java/objective/taskboard/followup/FollowUpDataGenerator.java
- src/main/java/objective/taskboard/jira/JiraProperties.java
- src/main/resources/application-dev.properties
- src/test/java/objective/taskboard/followup/FollowUpDataGeneratorTest.java
- src/test/java/objective/taskboard/followup/FollowUpDataGeneratorTestBase.java
- src/test/java/objective/taskboard/followup/FollowUpDataGeneratorTransitionsTest.java
- src/test/resources/application-test.properties
Created new properties to restrict the level subtasks on FollowUp, only on the tabs regarding the CFD graph.
> [Tools 1096] Created properties, restriction mechanisms and tests

- src/main/java/objective/taskboard/controller/WebhookController.java
- src/main/java/objective/taskboard/issueBuffer/IssueBufferService.java
- src/main/java/objective/taskboard/jira/JiraIssueService.java
- src/main/java/objective/taskboard/jira/JiraService.java
- src/main/java/objective/taskboard/jira/client/JiraIssueDto.java
- src/main/java/objective/taskboard/jira/data/WebHookBody.java
- src/main/java/objective/taskboard/task/IssueTypeEventProcessorFactory.java
- src/test/java/objective/taskboard/issueBuffer/IssueBufferServiceTest.java
- src/test/java/objective/taskboard/issueBuffer/WebhookControllerTest.java
- src/test/java/objective/taskboard/jira/client/JSONObjectAdapterTest.java
- changed Map<String, Object> to JiraIssueDto and JiraUserDto
- using getIssueByKeyAsMaster instead of searchIssueByKey
- removed some unused methods
> [TOOLS-560] refactored WebHookBody

- src/main/java/objective/taskboard/followup/AnalyticsTransitionsDataSet.java
- src/main/java/objective/taskboard/followup/FollowUpFacade.java
- src/main/java/objective/taskboard/followup/FollowUpReportGenerator.java
- src/main/java/objective/taskboard/followup/FollowUpTransitionsDataProvider.java
- src/main/java/objective/taskboard/followup/WipDataSet.java
- src/main/java/objective/taskboard/followup/WipRow.java
- src/main/java/objective/taskboard/followup/kpi/IssueStatusFlow.java
- src/main/java/objective/taskboard/followup/kpi/IssueStatusFlowFactory.java
- src/main/java/objective/taskboard/followup/kpi/NoDateStatusTransition.java
- src/main/java/objective/taskboard/followup/kpi/StatusTransition.java
- src/main/java/objective/taskboard/followup/kpi/StatusTransitionChain.java
- src/main/java/objective/taskboard/followup/kpi/TerminalStateTransition.java
- src/main/java/objective/taskboard/followup/kpi/WipKPIService.java
- src/main/java/objective/taskboard/jira/JiraProperties.java
- src/test/java/objective/taskboard/followup/FollowUpDataGeneratorTransitionsTest.java
- src/test/java/objective/taskboard/followup/FollowUpFacadeTest.java
- src/test/java/objective/taskboard/followup/FollowUpReportGeneratorTest.java
- src/test/java/objective/taskboard/followup/WipKpiServiceTest.java
- src/test/java/objective/taskboard/followup/kpi/IssueStatusFlowTest.java
- src/test/java/objective/taskboard/followup/kpi/StatusTransitionTest.java
- src/test/resources/application-test.properties
Create mechanisms to extract WIP KPI and next KPI's to be developed.
> [TOOLS-1145] WIP KPI on Followup Report

- src/main/java/objective/taskboard/google/SpreadsheetsManager.java
- src/main/java/objective/taskboard/sizingImport/SizingImportValidator.java
- src/main/resources/static/elements/taskboard/sizing-import.html
- src/test/java/objective/taskboard/it/IssueDetails.java
- When the stored google credential doesn't have access to the document (permission denied), it is removed and the user is prompted to give access to the document again
- Show appropriate error messages in the front end when the having problems accessing the sizing spreadsheet in google
> [TOOLS-1273] Fixes some sizing import issues

- src/main/resources/static/elements/taskboard/board-lane.html
- src/main/resources/static/elements/taskboard/board-step.html
- src/main/resources/static/elements/taskboard/board-table.html
- src/main/resources/static/elements/taskboard/lane-resizer.html
- src/main/resources/static/scripts/taskboard.js
- Bugfix: Transition to right step when the board is segregated by team
- Bugfix: Right issue count when the board is segregated by team
- board-table, board-lane and board-step clean
> [TOOLS-1263] Bugfix: Behaviors when the board is segregated by team

- src/main/java/objective/taskboard/controller/CardDto.java
- src/main/java/objective/taskboard/data/Issue.java
- src/main/java/objective/taskboard/data/Subtask.java
- src/main/java/objective/taskboard/issueBuffer/IssueBufferService.java
- src/test/java/objective/taskboard/data/IssueTest.java
- src/test/java/objective/taskboard/it/CardOpenUrlIT.java
Also, subtask list in the parent card are now ordered by issue key
> [TOOLS-1361] Parent changes should be notified to the clients

- src/main/java/objective/taskboard/controller/WipKPIController.java
- src/main/java/objective/taskboard/followup/WipChartDataSet.java
- src/main/java/objective/taskboard/followup/WipDataPoint.java
- src/main/java/objective/taskboard/followup/WipKPIDataProvider.java
- src/main/java/objective/taskboard/followup/kpi/IssueStatusFlowService.java
- src/main/java/objective/taskboard/followup/kpi/KPIUsingStatusService.java
- src/main/resources/static/elements/dashboard-elements.html
- src/main/resources/static/elements/taskboard/kpis/kpis-dashboard.html
- src/main/resources/static/elements/taskboard/kpis/widget-cfd.html
- src/main/resources/static/elements/taskboard/kpis/widget-progress-chart.html
- src/main/resources/static/elements/taskboard/kpis/widget-wip.html
- src/main/resources/static/elements/taskboard/kpis/widget-wrap.html
- src/test/java/objective/taskboard/controller/WipKpiControllerTest.java
- src/test/java/objective/taskboard/followup/ThroughputKPIServiceTest.java
- src/test/java/objective/taskboard/followup/WipKpiDataProviderTest.java
- src/test/java/objective/taskboard/followup/WipKpiServiceTest.java
- src/test/java/objective/taskboard/followup/kpi/IssueStatusFlowBuilder.java
- Refactoring to transform IssueStatusFlowFactoy into Service
- WIP KPI Chart Back-end
- WIP KPI Chart Front-emd
> [TOOLS-1506] WIP KPI Chart

- src/main/resources/static/elements/taskboard/kpis/widget-cfd.html
> [TOOLS-1517] Rescaling Y Axis CFD chart

- src/main/resources/kpi.properties
- src/test/resources/kpi.properties
Fixing kpi.properties on test
Adding a skeleton to the main/resource
> [TOOLS-1316] Kpi Properties

- src/main/java/objective/taskboard/followup/IssueTransitionService.java
- src/main/java/objective/taskboard/followup/kpi/IssueKpi.java
- src/main/java/objective/taskboard/followup/kpi/transformer/IssueKpiDataItemAdapterFactory.java
- src/test/java/objective/taskboard/followup/IssueTransitionServiceTest.java
- src/test/java/objective/taskboard/followup/kpi/FullCycleEffortTest.java
- src/test/java/objective/taskboard/followup/kpi/enviroment/IssueKpiBuilder.java
- src/test/java/objective/taskboard/followup/kpi/enviroment/KPIEnvironmentBuilder.java
- src/test/java/objective/taskboard/followup/kpi/transformer/IssueKpiDataItemAdapterFactoryTest.java
Fix error + defensive code
Increasing Tests Coverage
Fix typo
> [TOOLS-1918] Fix error when there is no status to calculate transitions

- src/main/resources/static/elements/taskboard/kpis/widget-throughput.html
- src/main/resources/static/elements/taskboard/kpis/widget-wip.html
- src/main/resources/static/scripts/chart-utils.js
- src/main/resources/static/scripts/issueTypesFilter.js
- src/main/resources/templates/followup-dashboard.html
Extracting filter to a component, fixing the bug
> [TOOLS-1917] Fix type filter toggle on WIP/TP chart

- src/main/resources/static/elements/taskboard/kpis/widget-cfd.html
- src/main/resources/static/elements/taskboard/kpis/widget-throughput.html
- src/main/resources/static/elements/taskboard/kpis/widget-wip.html
- src/main/resources/static/scripts/chart-utils.js
- src/main/resources/static/scripts/dc-date-range-charts-service.js
CFD chart translated to Highcharts.
> [TOOLS-1747] CFD Highcharts

- src/main/resources/static/elements/taskboard/kpis/widget-cfd.html
- src/main/resources/static/elements/taskboard/kpis/widget-wip.html
- src/main/resources/static/scripts/chart-utils.js
Fixed minor conflicts from previous merge not detected earlier
> [TOOLS-1747] Fix Wip chart

- src/main/java/objective/taskboard/followup/kpi/DatedStatusTransition.java
- src/main/java/objective/taskboard/followup/kpi/StatusTransition.java
- src/test/java/objective/taskboard/followup/kpi/SubtaskWorklogDistributorTest.java
Fixed when issue is done at the same day its starts doing;
Fixed when issue pass through all statuses at the same day
> [TOOLS-1977] Fix Wrong worklog distribution

- src/main/java/objective/taskboard/followup/kpi/IssueKpiService.java
- src/main/java/objective/taskboard/followup/kpi/KPIUsingStatusService.java
- src/main/java/objective/taskboard/followup/kpi/KpiLevel.java
- src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeChartDataSet.java
- src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeDataPoint.java
- src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeFilter.java
- src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIController.java
- src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIDataProvider.java
- src/main/java/objective/taskboard/utils/DateTimeUtils.java
- src/main/resources/static/elements/dashboard-elements.html
- src/main/resources/static/elements/taskboard/kpis/kpis-dashboard.html
- src/main/resources/static/elements/taskboard/kpis/widget-touch-time.html
- src/main/resources/static/scripts/chart-utils.js
- src/test/java/objective/taskboard/followup/kpi/FullCycleEffortTest.java
- src/test/java/objective/taskboard/followup/kpi/IssueKpiServiceTest.java
- src/test/java/objective/taskboard/followup/kpi/enviroment/KPIEnvironmentBuilder.java
- src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeFilterTest.java
- src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIControllerTest.java
- src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIDataProviderTest.java
- src/test/resources/kpi.properties
Touch Time by Issues Back-end and Front-end;
> [TOOLS-1896] Touch Time by Issues

- src/main/resources/static/elements/taskboard/kpis/widget-cfd.html
- src/main/resources/static/elements/taskboard/kpis/widget-progress-chart.html
- src/main/resources/static/elements/taskboard/kpis/widget-throughput.html
- src/main/resources/static/elements/taskboard/kpis/widget-touch-time.html
- src/main/resources/static/elements/taskboard/kpis/widget-wip.html
- src/main/resources/static/scripts/chart-utils.js
- src/main/resources/static/scripts/dc-date-range-charts-service.js
- src/main/resources/static/styles/highcharts-custom.css
- src/main/resources/templates/followup-dashboard.html
* Ticks using min pixel size to avoid rotation;
* Removing title from charts by default;
* Removing chart's title as key when registering chart in dc-date-range-service;
> [TOOLS-2038] Highcharts charts adjustments

- core/src/test/java/objective/taskboard/testUtils/DateTimeUtilSupport.java
- kpis/src/main/java/objective/taskboard/followup/WeekRangeNormalizer.java
- kpis/src/main/java/objective/taskboard/followup/kpi/IssueKpi.java
- kpis/src/main/java/objective/taskboard/followup/kpi/ProjectRangeByConfiguration.java
- kpis/src/main/java/objective/taskboard/followup/kpi/ProjectTimelineRange.java
- kpis/src/main/java/objective/taskboard/followup/kpi/StatusTransition.java
- kpis/src/main/java/objective/taskboard/followup/kpi/WeekTimelineRange.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/KpiValidationException.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeByWeekDataProvider.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeChartByWeekDataPoint.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeChartByWeekDataSet.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeFilter.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIController.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIDataProvider.java
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeProvider.java
- kpis/src/test/java/objective/taskboard/followup/WeekRangeNormalizerTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/FullCycleEffortTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/IssueKpiServiceTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/IssueKpiTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/ProjectRangeByConfigurationTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/StatusTransitionTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/TouchTimeByWeekDataProviderTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KPIEnvironmentBuilder.java
- kpis/src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIControllerTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIDataProviderTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/transformer/IssueKpiDataItemAdapterFactoryTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/transformer/IssueKpiTransformerTest.java
+ some cleanings
+ some minor reestructuring
> [TOOLS-1897] Touch Time by Week - BE

- kpis/src/main/java/objective/taskboard/followup/kpi/ChildrenWorklogDistributor.java
- kpis/src/main/java/objective/taskboard/followup/kpi/StatusTransition.java
- kpis/src/main/java/objective/taskboard/followup/kpi/SubtaskWorklogDistributor.java
- kpis/src/test/java/objective/taskboard/followup/kpi/IssueKpiAsserter.java
- kpis/src/test/java/objective/taskboard/followup/kpi/IssueKpiTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/StatusTransitionAsserter.java
- kpis/src/test/java/objective/taskboard/followup/kpi/StatusTransitionTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/SubtaskCycleEffortScenariosTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLKpi.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/IssueKpiMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiEnvironment.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiPropertiesMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/TransitionsBuilder.java
- kpis/src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeFilterTest.java
Added the stucture ante the definitions.
Another task will be created to finish the migrations
> [TOOLS-2044] Creating new KpiEnvironment and DSL's

- core/src/main/resources/static/scripts/chart-utils.js
- kpis/src/main/resources/static/elements/taskboard/kpis/widget-touch-time.html
* Order the plot data by total effort in descending order;
> [TOOLS-2040] Ordering TouchTime data by total effort.

- dashboard/src/main/resources/static/elements/dashboard-elements.html
- dashboard/src/main/resources/static/scripts/chart-utils.js
- kpis/src/main/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIController.java
- kpis/src/main/resources/static/elements/taskboard/kpis/kpis-dashboard.html
- kpis/src/main/resources/static/elements/taskboard/kpis/widget-touch-time-issues.html
- kpis/src/main/resources/static/elements/taskboard/kpis/widget-touch-time-weekly.html
- kpis/src/main/resources/static/styles/highcharts-custom.css
- kpis/src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIControllerTest.java
* Refactoring Touch Time by Issues to avoid conflicts with Touch Time by Week;
* Extract inline style to highcharts-custom.css;
* Moving chart-utils.js from core to dashboard;
> [TOOLS-1987] Touch Time by Week chart;

- kpis/src/main/java/objective/taskboard/followup/kpi/ChildrenWorklogDistributor.java
- kpis/src/main/java/objective/taskboard/followup/kpi/IssueKpi.java
- kpis/src/main/java/objective/taskboard/followup/kpi/StatusTransition.java
- kpis/src/main/java/objective/taskboard/followup/kpi/properties/IssueTypeChildrenStatusHierarchy.java
- kpis/src/main/java/objective/taskboard/followup/kpi/transformer/IssueKpiTransformer.java
- kpis/src/test/java/objective/taskboard/followup/kpi/ChildrenWorklogDistributorTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/FeatureCycleEffortTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/IssueKpiAsserter.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLBehavior.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLKpi.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/IssueKpiMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiEnvironment.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiPropertiesMocker.java
* Improve DSLKpi with method 'when' and Behaviors;
* Refactoring some methods' names in DSLKpi;
> [TOOLS-2126] Fix children worklogs distribution.

- kpis/src/test/java/objective/taskboard/followup/kpi/ChildrenWorklogDistributorTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLBehavior.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLKpi.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLSimpleBehavior.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/IssueKpiMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/IssueKpiServiceMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/JiraPropertiesMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiEnvironment.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiPropertiesMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeFilterTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/touchTime/TouchTimeKPIDataProviderTest.java
* DSL increments;
* Rewrite old tests using new DSL: ChildrenWorklogDistributorTest, TouchTimeKPIDataProviderTest;
> [TOOLS-2071] Refactoring tests to DSL.

- application/src/test/java/objective/taskboard/it/IssueDetails.java
- cardboard/src/main/resources/static/elements/taskboard/issue-detail.html
> [TOOLS-2138] - Edit card description on taskboard

- dashboard/src/main/resources/static/scripts/chart-utils.js
- kpis/src/main/java/objective/taskboard/followup/PlannedVsBallparkChartData.java
- kpis/src/main/resources/static/elements/taskboard/kpis/widget-planned-x-ballpark.html
Replacing the dc.js to Highcharts.js into Planned X Ballpark chart
> [TOOLS-1751] Planned x Ballpark

- core/src/main/java/objective/taskboard/issueBuffer/IssueBufferService.java
- core/src/main/java/objective/taskboard/jira/JiraIssueService.java
- core/src/main/java/objective/taskboard/jira/JiraSearchService.java
- core/src/main/java/objective/taskboard/jira/JiraService.java
- core/src/main/java/objective/taskboard/task/IssueTypeEventProcessorFactory.java
- core/src/test/java/objective/taskboard/issueBuffer/IssueBufferServiceTest.java
- core/src/test/java/objective/taskboard/issueBuffer/WebhookControllerTest.java
- jira-client/src/main/java/objective/taskboard/jira/client/JiraIssueDto.java
- test-support/src/main/java/objective/taskboard/testUtils/JiraMockServer.java
- Unified issue fetching from jira
> [TOOLS-2221] bugfix issues limited to 20 worklogs

- core/src/main/java/objective/taskboard/controller/WebhookController.java
- core/src/main/java/objective/taskboard/issueBuffer/IssueBufferService.java
- core/src/main/java/objective/taskboard/jira/JiraIssueService.java
- core/src/main/java/objective/taskboard/jira/JiraService.java
- core/src/main/java/objective/taskboard/task/IssueTypeEventProcessorFactory.java
- core/src/test/java/objective/taskboard/issueBuffer/IssueBufferServiceTest.java
- core/src/test/java/objective/taskboard/issueBuffer/WebhookControllerTest.java
- core/src/test/java/objective/taskboard/issueBuffer/WebhookControllerTestDSL.java
- jira-client/src/main/java/objective/taskboard/jira/client/JiraIssueDto.java
- test-support/src/main/java/objective/taskboard/testUtils/JiraMockServer.java
> [TOOLS-2221] reverting using search to fetch jira's issues

- dashboard/src/main/resources/static/scripts/chart-utils.js
Fix the size of the pie charts by updating data labels to show only percentages.
> [TOOLS-2251] Hotfix: Piecharts data labels

- core/bower.json
* Upgrade Highcharts from 6.x to 7.x;
* Fix bower.json extra-resolution;
> [TOOLS-2167] Cycle Time Front-end (Highcharts Upgrade)

- kpis/src/main/resources/static/elements/taskboard/kpis/widget-touch-time-issues.html
* Fix the logic of filtering ranges by timeline, so that some missed issues can be included now.
> [TOOLS-2283] Touch Time Chart Filter Fix

- dashboard/src/main/resources/static/scripts/chart-utils.js
* Fix zoom behavior after legend filter is applied to stacked charts.
> [TOOLS-2305] Fix Zoom after legend filter

- kpis/src/main/java/objective/taskboard/followup/kpi/ChildrenWorklogDistributor.java
- kpis/src/main/java/objective/taskboard/followup/kpi/DatedStatusTransition.java
- kpis/src/main/java/objective/taskboard/followup/kpi/IssueKpi.java
- kpis/src/main/java/objective/taskboard/followup/kpi/IssueKpiService.java
- kpis/src/main/java/objective/taskboard/followup/kpi/StatusTransition.java
- kpis/src/main/java/objective/taskboard/followup/kpi/StatusTransitionChain.java
- kpis/src/main/java/objective/taskboard/followup/kpi/SubtaskWorklogDistributor.java
- kpis/src/main/java/objective/taskboard/followup/kpi/ZonedWorklog.java
- kpis/src/main/java/objective/taskboard/followup/kpi/cycletime/CycleTimeDataProvider.java
- kpis/src/main/java/objective/taskboard/followup/kpi/cycletime/CycleTimeKpiFactory.java
- kpis/src/main/java/objective/taskboard/followup/kpi/leadtime/LeadTimeKpiDataProvider.java
- kpis/src/main/java/objective/taskboard/followup/kpi/leadtime/LeadTimeKpiFactory.java
- kpis/src/main/java/objective/taskboard/followup/kpi/transformer/IssueKpiTransformer.java
- kpis/src/test/java/objective/taskboard/followup/kpi/IssueKpiAsserter.java
- kpis/src/test/java/objective/taskboard/followup/kpi/StatusTransitionAsserter.java
- kpis/src/test/java/objective/taskboard/followup/kpi/SubtaskTouchTimeScenariosTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/SubtaskWorklogDistributorTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/cycletime/CycleTimeControllerTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/DSLKpi.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/IssueKpiMocker.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/KpiEnvironment.java
- kpis/src/test/java/objective/taskboard/followup/kpi/enviroment/TransitionsBuilder.java
- kpis/src/test/java/objective/taskboard/followup/kpi/leadTime/LeadTimeControllerTest.java
- kpis/src/test/java/objective/taskboard/followup/kpi/transformer/IssueKpiTransformerTest.java
* Create a new class ZonedWorklog to use Worklog started as ZonedDateTime, so that facilitate Date manipulation when used.
> [TOOLS-2311] ZonedWorklog

- cardboard/src/test/java/objective/taskboard/filterPreferences/CardFieldFilterServiceTest.java
- cardboard/src/test/java/objective/taskboard/filterPreferences/UserPreferencesServiceTest.java
- core/src/main/java/objective/taskboard/data/IssuesConfiguration.java
- core/src/main/java/objective/taskboard/database/TaskboardConfigToLaneConfigurationTransformer.java
- core/src/main/java/objective/taskboard/database/TaskboardDatabaseService.java
- core/src/main/java/objective/taskboard/domain/converter/CardVisibilityEvalService.java
- core/src/main/java/objective/taskboard/domain/converter/StartDateStepService.java
- core/src/main/java/objective/taskboard/filter/LaneService.java
- core/src/test/java/objective/taskboard/domain/converter/CardVisibilityEvalServiceTest.java
- core/src/test/java/objective/taskboard/domain/converter/StartDateStepServiceTest.java
Reduced regular expression overuse by pre-converting string into integer representation
> [TOOLS-2527] limitInDays changed to Integer
